version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mlflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5001:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: trainer
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      TF_CPP_MIN_LOG_LEVEL: "2"
      PYTHONPATH: /app
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  mysql_data:
  mlflow_artifacts:
